<<<<<<< HEAD
AWS_ACCESS_KEY_ID: AKIAR7HIUIBLUQ6WJHBJ
AWS_SECRET_ACCESS_KEY: 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
=======
AWS_ACCESS_KEY_ID: AKIAWxxxx
AWS_SECRET_ACCESS_KEY: cNcNoZGRxxxxxxx
>>>>>>> 2a5eb8ea2c5481086d77c87869a328fdd3496b23
AWS_REGION: us-east-1
