- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - config.yml
  vars:
    keypair: my_keypair
    instance_type: t2.micro
    security_group: default
    image: ami-0a887e401f7654935
  tasks:
    - name: Launch instance
      ec2:
         aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         ec2_region: "{{ AWS_REGION }}"
         exact_count: 2
         count_tag:
           Name: PankajEC21
         instance_tags:
           Name: PankajEC21
         vpc_subnet_id: subnet-0fed02a76eecd6d17
         tenancy: dedicated         
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"
